### ISSUE TITLE
Feature request: (Auto-)Sortable Emojis

### ISSUE THREAD

**Issue by DoomDesign** [grubeninspekteur/BetterRBTV#22]
Collecting some community requests here for future development.

A feature was requested where the emojis in their native selection popup would either
1. be manually sortable (think drag'n'drop) or
2. sort themselves by usage (the most often used emojis move to the most prominent position)

My thoughts on this:
WhatsApp does this kind variation of 2., where an extra emoji tab is used to display the most recently used emojis. This would also be a solution most users could be familiar with, if the forementioned ways 1. & 2. are too complicated.

**Comment by grubeninspekteur** [comment]
I'd go for the most recently used solution as it is both less harder to implement and more consistent when someone asks where to find emoji x.

**Comment by DoomDesign** [comment]
So the WhatsApp style solution?

**Comment by grubeninspekteur** [comment]
Yes

**Comment by DoomDesign** [comment]
I'm working on this currently, will commit as soon as it's presentable!
