### ISSUE TITLE
Feature request: Doubleclick on username to insert it as a mention

### ISSUE THREAD

**Issue by DoomDesign** [grubeninspekteur/BetterRBTV#23]
Collecting some community requests here for future development.

A feature was requested, where a doubleclick on a username in the chat would create a mention for that name in the message input field, as an alternative to manually writing the name or tabbing through the user suggestions.

My thoughts:
Doesn't sound too hard to implement in theory, I could try to lay my hands on this ASAP.

**Comment by DoomDesign** [comment]
When I doubleclick on a name now, the caret is always placed BEFORE the inserted username. Is this the intended behaviour?

**Comment by grubeninspekteur** [comment]
Strange, it should always be **after** the user name. Can you give instructions to reproduce the bug?

**Comment by DoomDesign** [comment]
Hmmm, on my PC at work it works as intended by you. But at home, yesterday, it had that bug. I will try to research this and find out reproducable conditions ASAP.

**Comment by DoomDesign** [comment]
I couldn't replicate this issue. As I noticed it, it was constant, but the day after the feature was working as intended.
