### ISSUE TITLE
Works only after a refresh on YouTube Live

### ISSUE THREAD

**Issue by grubeninspekteur** [grubeninspekteur/BetterRBTV#26]
The new chat detection which enables the extension without a log in does not work on YouTube Live (not Gaming). Only after a refresh the necessary element is detected.

**Comment by DoomDesign** [comment]
maybe there is an YouTube-own event we could use to listen to?

**Comment by grubeninspekteur** [comment]
Content scripts are not allowed to interact with JavaScript already on the page

**Comment by grubeninspekteur** [comment]
Can't test now, but I suspect AJAX ruining everything. We could keep the check timer alive, which does not use much CPU, but is something I wanted to avert. Another possibility would be a MutationObserver for the part of the page that is replaced by AJAX. This would also work if you visit a live stream after visiting a live stream, i.e. you change the contents twice.
