### ISSUE TITLE
Feature request: Option to hide VIP badges

### ISSUE THREAD

**Issue by DoomDesign** [grubeninspekteur/BetterRBTV#27]
make the VIP badges hideable via option.

**Comment by grubeninspekteur** [comment]
Come to think of it, is this something we really want to support, even if it is only an option?

**Comment by DoomDesign** [comment]
Yeah I also thought, "why do you want to hide these tiny little icons" ? I mean, the VIPs shouldn't see themselves as better people, but that tiny badge is - at least for now - the only thing they can "earn" by becoming VIP...

**Comment by grubeninspekteur** [comment]
Closing as it is detrimental to channel owners if there is no visible VIP badge.
