### ISSUE TITLE
Chat flickers under high load

### ISSUE THREAD

**Issue by grubeninspekteur** [grubeninspekteur/BetterRBTV#33]
A user (Chrome/Mac OS X) reported constant flickering when there is a high number of incoming chat messages, which renders the add-on unusable. Investigation is underway, but there is a number of possible culprits: the scrollbar positioning required after inevitably changing the div's contents, and the type hint bug fix.

As this happens on a specific machine, it could be a bug related to Chrome's hardware acceleration. If we can't circumvent this, we could try: a) reduce the overall load so the renderer can catch on; b) optionally force Chrome to use software rendering for the scrollbar fix; c) see whether the scrollbar fix is still required and if yes, bind it to a timer so it is only executed every x ms, instead of every time a new message is appended.

Note that c) requires additional logic to check whether the user scrolled between the time we determined whether we need a fix and the point when we execute it.

**Comment by DoomDesign** [comment]
We also should check the importance of this bug. What I mean, is, how many users are affected by this? Is it worth the work? Could the bugfix introduce new bugs for all other users who don't experience this flickering?
Also, it has to be reproducable to be fixable. The user yet didn't say if the flickering also occurs with the plugin deactivated, for example.

**Comment by grubeninspekteur** [comment]
On rare occasions I encounter this bug myself, but not as frequent as the user. Reproducability is the main problem. I tried with artificial messages generated each ms, but with no luck.

**Comment by grubeninspekteur** [comment]
Closing as not reproduceable; still occurring rarely, but not a big nuisance.
