### ISSUE TITLE
Hiding of byline in input div does not resize div

### ISSUE THREAD

**Issue by grubeninspekteur** [grubeninspekteur/BetterRBTV#36]
With the save space option, we hide the byline of the chat input field. The div does not resize accordingly, making it hard clicking on the actual input area.

**Comment by DoomDesign** [comment]
Can't work on it right now, but a simple

`.live-chat-widget .comments-textarea { min-height: 32px !important; }`

should do the trick.

**Comment by grubeninspekteur** [comment]
It did, thanks!
