### ISSUE TITLE
Highlight highlights more prominently

### ISSUE THREAD

**Issue by grubeninspekteur** [grubeninspekteur/BetterRBTV#42]
Requested by a user: Make the custom user highlights more visible as an option

**Comment by DoomDesign** [comment]
ah now I get it, he means the "stalking list" highlights? :grinning:

**Comment by DoomDesign** [comment]
What about a blinking accent bar? :)

![2016-09-17_11-02-23](https://cloud.githubusercontent.com/assets/466316/18607197/72f34592-7cc6-11e6-8140-8cf8eff8f083.gif)

**Comment by grubeninspekteur** [comment]
Please don't give me 90's web pages flashbacks - literally.
