### ISSUE TITLE
Work in AMO reviewer request

### ISSUE THREAD

**Issue by grubeninspekteur** [grubeninspekteur/BetterRBTV#59]
> Comments:
> This version has been approved for the public.
> 
> Please note the following for the next update:
> 1) Your add-on's code includes instances of printing debugging information to the Console, which is generally not allowed in production add-ons. Please remove or disable such logging.
> 
> 2) Suggestion: You can use a loop to economize the code eg:
> var css = '';
> var n = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_';
> for (var i = 0, len = n.length; i < len; i++) {
>  css += `.yt-live-chat-text-message-renderer-0 img[src*="/-${n[i]}"] + #content #author-name { color: #47d288 ; })\n`;
> }

> 3) Style is test [sic; text]. For inserting text, textContent (or JQuery text) or createTextNode() should be used instead of innerHTML.
> eg: util.js
> 
> 4) Please consider not storing large CSS sytlesheets in executable JS files. Please include them as separate > files within your XPI.
> 
> Thank you for your contribution.

**Comment by DoomDesign** [comment]
regarding 2.: While their solution would be nice IF every username should get the same color (and even then there would be a far more simpler CSS solution), they didn't see the different defined color hex codes, it seems.

**Comment by grubeninspekteur** [comment]
The colors can be put into an array to address them in the same vein as the letters.
