### ISSUE TITLE
Bug: Shifting user names

### ISSUE THREAD

**Issue by DoomDesign** [grubeninspekteur/BetterRBTV#60]
Not yet reproducable, but occuring (only? or mainly?) on YT live (not gaming):

Sometimes, the user names for each message get shifted (so messages get a different user name displayed), as if they run out of sync. No users are blocked in my plugin options, but multiple (mainly the RBTV crew) are highlighted.

**Comment by grubeninspekteur** [comment]
Does the bug only occur under high load? I still haven't experienced it when visiting YT live sporadically.

**Comment by DoomDesign** [comment]
There's a good possibility, yes. Haven't used YT live under low load. Currently (6.3k viewers) the bug occurs.
